# Generated by Django 2.2.6 on 2020-06-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbitry', '0015_checkmask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkmask',
        ),
    ]
